require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BooleanSettingsController do

  # This should return the minimal set of attributes required to create a valid
  # BooleanSetting. As you add validations to BooleanSetting, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "key" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BooleanSettingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all boolean_settings as @boolean_settings" do
      boolean_setting = BooleanSetting.create! valid_attributes
      get :index, {}, valid_session
      assigns(:boolean_settings).should eq([boolean_setting])
    end
  end

  describe "GET show" do
    it "assigns the requested boolean_setting as @boolean_setting" do
      boolean_setting = BooleanSetting.create! valid_attributes
      get :show, {:id => boolean_setting.to_param}, valid_session
      assigns(:boolean_setting).should eq(boolean_setting)
    end
  end

  describe "GET new" do
    it "assigns a new boolean_setting as @boolean_setting" do
      get :new, {}, valid_session
      assigns(:boolean_setting).should be_a_new(BooleanSetting)
    end
  end

  describe "GET edit" do
    it "assigns the requested boolean_setting as @boolean_setting" do
      boolean_setting = BooleanSetting.create! valid_attributes
      get :edit, {:id => boolean_setting.to_param}, valid_session
      assigns(:boolean_setting).should eq(boolean_setting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BooleanSetting" do
        expect {
          post :create, {:boolean_setting => valid_attributes}, valid_session
        }.to change(BooleanSetting, :count).by(1)
      end

      it "assigns a newly created boolean_setting as @boolean_setting" do
        post :create, {:boolean_setting => valid_attributes}, valid_session
        assigns(:boolean_setting).should be_a(BooleanSetting)
        assigns(:boolean_setting).should be_persisted
      end

      it "redirects to the created boolean_setting" do
        post :create, {:boolean_setting => valid_attributes}, valid_session
        response.should redirect_to(BooleanSetting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boolean_setting as @boolean_setting" do
        # Trigger the behavior that occurs when invalid params are submitted
        BooleanSetting.any_instance.stub(:save).and_return(false)
        post :create, {:boolean_setting => { "key" => "invalid value" }}, valid_session
        assigns(:boolean_setting).should be_a_new(BooleanSetting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BooleanSetting.any_instance.stub(:save).and_return(false)
        post :create, {:boolean_setting => { "key" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boolean_setting" do
        boolean_setting = BooleanSetting.create! valid_attributes
        # Assuming there are no other boolean_settings in the database, this
        # specifies that the BooleanSetting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BooleanSetting.any_instance.should_receive(:update_attributes).with({ "key" => "MyString" })
        put :update, {:id => boolean_setting.to_param, :boolean_setting => { "key" => "MyString" }}, valid_session
      end

      it "assigns the requested boolean_setting as @boolean_setting" do
        boolean_setting = BooleanSetting.create! valid_attributes
        put :update, {:id => boolean_setting.to_param, :boolean_setting => valid_attributes}, valid_session
        assigns(:boolean_setting).should eq(boolean_setting)
      end

      it "redirects to the boolean_setting" do
        boolean_setting = BooleanSetting.create! valid_attributes
        put :update, {:id => boolean_setting.to_param, :boolean_setting => valid_attributes}, valid_session
        response.should redirect_to(boolean_setting)
      end
    end

    describe "with invalid params" do
      it "assigns the boolean_setting as @boolean_setting" do
        boolean_setting = BooleanSetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BooleanSetting.any_instance.stub(:save).and_return(false)
        put :update, {:id => boolean_setting.to_param, :boolean_setting => { "key" => "invalid value" }}, valid_session
        assigns(:boolean_setting).should eq(boolean_setting)
      end

      it "re-renders the 'edit' template" do
        boolean_setting = BooleanSetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BooleanSetting.any_instance.stub(:save).and_return(false)
        put :update, {:id => boolean_setting.to_param, :boolean_setting => { "key" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boolean_setting" do
      boolean_setting = BooleanSetting.create! valid_attributes
      expect {
        delete :destroy, {:id => boolean_setting.to_param}, valid_session
      }.to change(BooleanSetting, :count).by(-1)
    end

    it "redirects to the boolean_settings list" do
      boolean_setting = BooleanSetting.create! valid_attributes
      delete :destroy, {:id => boolean_setting.to_param}, valid_session
      response.should redirect_to(boolean_settings_url)
    end
  end

end
